site_name: 42Hz Dev Docs
site_url: https://mkdocs.42hzs.com
site_description: Infrastructure & Backend Documentation
site_author: Shin Dongyeol

theme:
  name: material
  language: ko
  features:
    - navigation.expand

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Home: index.md
  - Infrastructure:
    - CI/CD & Telegram:
      - CI/CD: infrastructure/cicd/index.md
      - Telegram:
        - Check: infrastructure/cicd/telegram_check.md
        - Send_Message: infrastructure/cicd/telegram_message.md
    - Grafana:
      - Setting: infrastructure/grafana/index.md
      - Domain: infrastructure/grafana/grafana_domain_cloudflare.md
    - Docker: infrastructure/docker/index.md