site_name: 42Hz Dev Docs
site_url: https://mkdocs.42hzs.com
site_description: Infrastructure & Backend Documentation
site_author: Shin Dongyeol

theme:
  name: material
  language: ko

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Home: index.md
  - Infrastructure:
    - CI/CD: infrastructure/cicd/index.md
    - Grafana: infrastructure/grafana/index.md 